CREATE SEQUENCE SEQ_ITEM_ID START WITH 1 INCREMENT BY 1 CACHE 100;
CREATE SEQUENCE HIBERNATE_SEQUENCE START WITH 1 INCREMENT BY 1 CACHE 100;

CREATE TABLE ITEM (
    ID      INTEGER         NOT NULL
  , NAME    VARCHAR(100)    NOT NULL
  , CONSTRAINT PK_ITEM PRIMARY KEY (ID)
);

GRANT SELECT, UPDATE ON SEQ_ITEM_ID TO EXAMPLEADMIN;
GRANT SELECT, UPDATE ON HIBERNATE_SEQUENCE ID TO EXAMPLEADMIN;

GRANT SELECT, INSERT, UPDATE, DELETE ON ITEM TO EXAMPLEADMIN;

INSERT INTO ITEM (ID, NAME) VALUES (NEXTVAL('SEQ_ITEM_ID'), 'This is item 1!');
INSERT INTO ITEM (ID, NAME) VALUES (NEXTVAL('SEQ_ITEM_ID'), 'Another item!');
INSERT INTO ITEM (ID, NAME) VALUES (NEXTVAL('SEQ_ITEM_ID'), 'Yes');
INSERT INTO ITEM (ID, NAME) VALUES (NEXTVAL('SEQ_ITEM_ID'), 'Woohoo!');
INSERT INTO ITEM (ID, NAME) VALUES (NEXTVAL('SEQ_ITEM_ID'), 'Visit http://www.craigstjean.com/');
INSERT INTO ITEM (ID, NAME) VALUES (NEXTVAL('SEQ_ITEM_ID'), 'On Twitter as @crstj');
INSERT INTO ITEM (ID, NAME) VALUES (NEXTVAL('SEQ_ITEM_ID'), 'WebSphere');
INSERT INTO ITEM (ID, NAME) VALUES (NEXTVAL('SEQ_ITEM_ID'), 'JPA');
INSERT INTO ITEM (ID, NAME) VALUES (NEXTVAL('SEQ_ITEM_ID'), 'Spring');
INSERT INTO ITEM (ID, NAME) VALUES (NEXTVAL('SEQ_ITEM_ID'), 'Hibernate');
COMMIT;
